### ISSUE TITLE
ReferenceError: Template is not defined

### ISSUE THREAD

**Issue by linhaiwei123** [DiscoverMeteor/Microscope#286]
i just follow the tutorial in chapter of template.

here is the log in the browser:
`C:\Users\HP\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
						throw(ex);
						      ^
ReferenceError: Template is not defined
    at meteorInstall.templates.posts.posts_list.js (templates/posts/posts_list.js:15:1)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    at C:\Users\HP\Desktop\meteorWorkSpace\microscope\.meteor\local\build\programs\server\app\app.js:40:1
    at C:\Users\HP\Desktop\meteorWorkSpace\microscope\.meteor\local\build\programs\server\boot.js:283:10
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\HP\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
    at C:\Users\HP\Desktop\meteorWorkSpace\microscope\.meteor\local\build\programs\server\boot.js:133:5
Exited with code: 8
Your application is crashing. Waiting for file change.`

**Comment by linhaiwei123** [comment]
i work for me when i move the folder of template from root to folder of client
